### ISSUE TITLE
Error 404 in downloading zlib-1.2.8.tar.gz (and possibly more)

### ISSUE THREAD

**Issue by happysmash27** [LuxCoreRender/LinuxCompileDeps#2]
When trying to run ./download.sh, it fails in finding zlib-1.2.8.tar.gz: 

```
LinuxCompileDeps % ./download.sh
 * Checking distfiles
 * File zlib-1.2.8.tar.gz
 * Resume downloading zlib-1.2.8.tar.gz
--2020-11-24 01:52:03--  http://zlib.net/zlib-1.2.8.tar.gz
Ni solvigas zlib.net... 85.187.148.2
Konektado al zlib.net|85.187.148.2|:80... konektita.
HTTP peto sendita, ni atendas respondon... 404 Not Found
2020-11-24 01:52:03 ERARO 404: Not Found.

 !!! Hash mismatch for zlib-1.2.8.tar.gz
```

It may fail in downloading other libraries too, but I am not certain it does yet, as it stops immediately after failing to download zlib.

**Comment by Dade916** [comment]
Read the reame file, you don't need the download.sh script.

**Comment by happysmash27** [comment]
It turns out this isn't very important, as the LinuxCompile script just downloads a tarball of the entire thing anyway.

**Comment by happysmash27** [comment]
Just figured that out; it appears that the LinuxCompile scripts just download a tarball of the entire thing, making this unneeded. 

I'm not sure which readme file you are talking about though, as this repository does not contain one.

**Comment by Dade916** [comment]
You don't need this one, this is the repository to use: https://github.com/LuxCoreRender/LinuxCompile (and read the README there).
